### ISSUE TITLE
Initial logo design

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko#2]

**Comment by bazzika** [comment]
[logo18.svg.zip](https://github.com/zorko-io/zorko/files/1609763/logo18.svg.zip)

**Comment by bazzika** [comment]
[zirko4varNEEEEww ALLname var2.svg — копия.zip](https://github.com/zorko-io/zorko/files/1778318/zirko4varNEEEEww.ALLname.var2.svg.zip)
[zirko4varNEEEEww.svg — копия.zip](https://github.com/zorko-io/zorko/files/1778319/zirko4varNEEEEww.svg.zip)
[zorkoAllvar1.svg.zip](https://github.com/zorko-io/zorko/files/1778320/zorkoAllvar1.svg.zip)
[zirko4var.svg.zip](https://github.com/zorko-io/zorko/files/1778321/zirko4var.svg.zip)
